### ISSUE TITLE
可以上传完整的项目代码吗？

### ISSUE THREAD

**Issue by wsy-yjys** [wsjxdy/mFDSD#1]
这是一项很棒的工作，深受启发，请问方便上传完整的项目代码吗，想进一步深入的理解下代码细节

**Comment by wsjxdy** [comment]
你好，我对项目的完整代码进行了初步格式清洗与必要步骤的注释，并将其打包上传到百度网盘（链接：https://pan.baidu.com/s/1J-yfy68HXubGn7YTGSjUQA?pwd=2jm5 提取码：2jm5）。
请注意：
（1）本文基于Yolov5进行构建，因此项目环境配置请按照yolov5环境配置即可（https://github.com/ultralytics/yolov5）
（2）本文增量数据读取方式与相关函数与faster ilod一致，因此项目数据集构建请务必按照Faster ilod中数据集构建方式进行构建（https://github.com/CanPeng123/Faster-ILOD）

**Comment by wsy-yjys** [comment]
非常感谢~
